insert into main.COMPANY_ACCOUNT (name, purpose)
values  ('Payroll', 'used for employee salary and benefits payments.'),
        ('Accounts Receivable', 'used to receive and manage payments from customers'),
        ('Accounts Payable', 'used to manage and pay bills and invoices to vendors and suppliers'),
        ('Operating', 'used for day-to-day business expenses such as rent, utilities, and supplies.'),
        ('Tax', 'used to set aside funds for tax payments.'),
        ('Investment', 'used to invest surplus cash and earn interest or returns.'),
        ('Merchant', 'used to receive payments from credit and debit card transactions.'),
        ('Reserve', 'used to set aside funds for emergencies or unexpected expenses.'),
        ('Petty Cash', 'used to make small, immediate cash purchases'),
        ('Escrow', 'used to hold funds for a specific purpose, such as a real estate transaction.'),
        ('Foreign Currency', 'used to manage transactions in a foreign currency'),
        ('Line of Credit', 'used to access credit for short-term financing needs.'),
        ('Capital Expenditure', 'used to fund long-term investments in assets such as equipment or property.'),
        ('Insurance', 'used to manage insurance premiums and claims.'),
        ('Vendor Deposits', 'used to hold deposits paid to vendors or suppliers.'),
        ('Sales Tax', 'used to collect and remit sales taxes.'),
        ('Contingency Fund', 'used to hold funds for unexpected expenses or contingencies.'),
        ('Legal Fees', 'used to pay for legal services and fees.'),
        ('Marketing', 'used to fund marketing and advertising campaigns.'),
        ('Research and Development', 'used to fund research and development initiatives.');