insert into main.CUSTOMER (email, fName, lName)
values  ('Bowers858@gmail.com', 'Margaret', 'Bowers'),
        ('Roth619@yahoo.com', 'Shane', 'Roth'),
        ('Wiley608@outlook.com', 'Michelle', 'Wiley'),
        ('Griffin731@gmail.com', 'David', 'Griffin'),
        ('Bowman673@hotmail.com', 'Kara', 'Bowman'),
        ('Bowman237@yahoo.com', 'Jeffrey', 'Bowman'),
        ('Harrison091@hotmail.com', 'Benjamin', 'Harrison'),
        ('Ashley918@yahoo.com', 'Andrea', 'Ashley'),
        ('Donovan940@outlook.com', 'Jeffrey', 'Donovan'),
        ('Petersen505@gmail.com', 'Gerald', 'Petersen'),
        ('Cruz877@gmail.com', 'Samantha', 'Cruz'),
        ('Davis836@outlook.com', 'Mia', 'Davis'),
        ('Jackson661@aol.com', 'Jonathan', 'Jackson'),
        ('Schultz605@yahoo.com', 'Jacob', 'Schultz'),
        ('Burnett780@outlook.com', 'Matthew', 'Burnett'),
        ('Mcclure952@outlook.com', 'Shaun', 'Mcclure'),
        ('Mitchell662@hotmail.com', 'Faith', 'Mitchell'),
        ('Coleman608@aol.com', 'Sarah', 'Coleman'),
        ('Huffman380@yahoo.com', 'Jeffrey', 'Huffman'),
        ('Reyes157@gmail.com', 'Kayla', 'Reyes');