insert into main.MONEY_TRANSFER (orderId, accountName)
values  (1, 'Capital Expenditure'),
        (2, 'Insurance'),
        (3, 'Escrow'),
        (4, 'Investment'),
        (5, 'Contingency Fund'),
        (6, 'Insurance'),
        (7, 'Line of Credit'),
        (8, 'Marketing'),
        (9, 'Sales Tax'),
        (10, 'Sales Tax'),
        (11, 'Sales Tax'),
        (12, 'Capital Expenditure'),
        (13, 'Accounts Payable'),
        (14, 'Foreign Currency'),
        (15, 'Accounts Payable'),
        (16, 'Legal Fees'),
        (17, 'Payroll'),
        (18, 'Research and Development'),
        (19, 'Legal Fees'),
        (20, 'Reserve');