insert into main.PUBLISHER (id, name)
values  (1, 'Sybex'),
        (2, 'McGraw-Hill Osborne Media'),
        (3, 'John Wiley & Sons'),
        (4, 'Morgan Kaufmann'),
        (5, 'Schmidt Ink, Inc.'),
        (6, 'Addison-Wesley Publishing'),
        (7, 'Macromedia Press'),
        (8, 'Wrox Press Inc'),
        (9, 'Berkley Pub Group'),
        (10, 'Penguin USA'),
        (11, 'O''Reilly & Associates'),
        (12, 'McGraw-Hill Trade'),
        (13, 'Picador'),
        (14, 'St. Martin''s Press'),
        (15, 'Crown Pub'),
        (16, 'Little Brown & Company'),
        (17, 'Simon & Schuster'),
        (18, 'HarperCollins'),
        (19, 'Jossey-Bass'),
        (20, 'Multnomah Publishers Inc.'),
        (21, 'Perennial'),
        (22, 'Dell Pub Co'),
        (23, 'Harlequin'),
        (24, 'Viking Press'),
        (25, 'Perseus Publishing'),
        (26, 'Random House'),
        (27, 'Knopf'),
        (28, 'Wolfram Media, Inc.'),
        (29, 'Fireside'),
        (30, 'Random House Trade Paperbacks'),
        (31, 'Gibbs Smith Publisher'),
        (32, 'Taunton Pr'),
        (33, 'Vendome Pr'),
        (34, 'Clarkson N. Potter'),
        (35, 'MIT Press'),
        (36, 'McGraw-Hill/Irwin'),
        (37, 'South-Western College Pub'),
        (38, 'Prentice Hall'),
        (39, 'Warner Books'),
        (40, 'Scribner'),
        (41, 'Pocket Books'),
        (42, 'Pantheon Books'),
        (43, 'Del Rey'),
        (44, 'Doubleday'),
        (45, 'Donald M. Grant Publisher, Inc.'),
        (46, 'Vintage Books'),
        (47, 'Scribner Paperback Fiction'),
        (48, 'Harvest Books'),
        (49, 'Harperperennial Library'),
        (50, 'W.W. Norton & Company'),
        (51, 'Harvard Univ Pr'),
        (52, 'Prentice Hall PTR'),
        (53, 'New Riders Publishing'),
        (54, 'Ballantine Books'),
        (55, 'Back Bay Books'),
        (56, 'Anchor Books'),
        (57, 'Putnam Pub Group'),
        (58, 'Silhouette'),
        (59, 'Lark Books'),
        (60, 'Harper');