insert into main.WISHLIST (customerEmail, name, privacy)
values  ('Bowman237@yahoo.com', 'Must-Haves', 'Public'),
        ('Reyes157@gmail.com', 'Dream List', 'Public'),
        ('Ashley918@yahoo.com', 'Future Treasures', 'Private'),
        ('Davis836@outlook.com', 'Wishlist Wonders', 'Private'),
        ('Donovan940@outlook.com', 'Bucket List Books', 'Public'),
        ('Burnett780@outlook.com', 'Heart''s Desires', 'Private'),
        ('Griffin731@gmail.com', 'Coveted Collection', 'Private'),
        ('Donovan940@outlook.com', 'Longing List', 'Public'),
        ('Burnett780@outlook.com', 'Wishful Thinking', 'Private'),
        ('Mcclure952@outlook.com', 'To Read and Own', 'Private'),
        ('Jackson661@aol.com', 'To Read and Own', 'Public'),
        ('Bowman237@yahoo.com', 'Desired Discoveries', 'Public'),
        ('Griffin731@gmail.com', 'Future Favorites', 'Public'),
        ('Cruz877@gmail.com', 'Bookish Bliss', 'Public'),
        ('Mcclure952@outlook.com', 'Literary Lust List', 'Private'),
        ('Reyes157@gmail.com', 'The Ultimate Wishlist', 'Private'),
        ('Mcclure952@outlook.com', 'Top Shelf Selections', 'Private'),
        ('Burnett780@outlook.com', 'Next-Level Novels', 'Public'),
        ('Bowman673@hotmail.com', 'Reading Resolutions', 'Public'),
        ('Mcclure952@outlook.com', 'Essential Reads', 'Private'),
        ('Bowers858@gmail.com', 'Most Wanted Manuscripts', 'Public');